version: '3'
services:
  # Zookeeper (required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  # Filebeat (to collect logs and send to Kafka)
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.3
    container_name: filebeat
    depends_on:
      - kafka
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/abdul-majid/java_projects/LogFlux/sample_logs:/home/abdul-majid/java_projects/LogFlux/sample_logs
    restart: unless-stopped

# Volumes for Kafka data persistence
volumes:
  kafka-data: